const SET_POS_TRANSA = "SET_POS_TRANSA";
const SET_USER = "SET_USER";
const TO_USER = "TO_USER";
const MORE_INFO = "MORE_INFO";
const R_BALANCE = "R_BALANCE";
const REMOVE_USER = `REMOVE_USER`;
export { SET_POS_TRANSA, SET_USER, TO_USER, MORE_INFO, R_BALANCE, REMOVE_USER };
